language: node_js

node_js:
  - "0.10"

env:
  global:
  - secure: |-
      TJnNSOFOHADdoVZAKZ9FwjbA8LPwWIp2uvCe25MVpEl8b3wQVWC4DFa4SDoJ
      yCdjMsQVjoGfUayL8+ukHYXdSRRSd0JUE0BW+vylVFHZ5JIfa4wdpdIPtRKb
      m88JW6pT39UWMrnrgZDFjz/ImXBHgadsBBsdvnJ9yHzqDMj2wkg=
  - secure: |-
      E4C0/Ns1iJulnUUro5udsR6WsOe9coTgr3krCkYqi6Tugj7eKSKcdMa4qPh5
      6dnsDI+qsqeG50OQHRJ3z2ZBb+MojfIB+f2zzjCV1VWYvWauJuMJIZ8e9IgZ
      GzJhnFPkRmQMRgN4/uVVZyTmhPQVE6CyrSstOHr2jsVDMjYAQFU=

install:
  - npm install -g grunt-cli
  - npm install

before_script:
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh -L | bash

notifications:
  email:
    on_success: never